astropy/astroplan

astroplan/core.py

Here's a really tiny PR to re-order the kwargs in `Observer` so you can initialize `Observer`s faster. In all of my examples I've had to use the `location` kwarg whenever initializing an example observatory, like this:
```python
obs = Observer(location=EarthLocation(...))
```
Often the observatory name isn't important, so I've reordered the kwargs to reflect the order of importance in the calculations (location, timezone, name), so you don't need to write the kwarg names each time, like this:
```python
obs = Observer(EarthLocation(...))
obs = Observer(EarthLocation(...), 'US/Hawaii')
obs = Observer(EarthLocation(...), 'US/Hawaii', 'Subaru')
```

Re-ordering Observer kwargs

---

astroplan/tests/test_utils.py
astroplan/utils.py
docs/getting_started.rst

At the start of the project I added a single dummy function and test.
Now that we have real code and tests, it should be removed, which is done in this PR.
@eteq – Can you please have a look and merge if it's OK and travis-ci passes?

Remove dummy test function

---

astroplan/core.py
astroplan/tests/test_core.py

Enhancement: `observer.is_night(time, [horizon])`
Is the sun below specified `horizon` at `time` for an `Observer`? This is a method I was writing for myself when coding up a use case, so I stuck it into `Observer` for everyone.

is_night convenience method

---

astroplan/core.py
astroplan/tests/test_sites.py

Making it easier to initialize an `Observer`object at a site via the `sites` module, as per a conversation with @eteq on Slack. 
Now to initialize an observer at Kitt Peak, for example:
```python
from astroplan import Observer
kpno = Observer.at_site("kpno")
```

Adding Observer.at_site class method

---

astroplan/core.py
astroplan/tests/test_core.py
dev/planning-example.py

Since writing up the API, we've migrated towards maximally descriptive method names, and one area that has been neglected is the set of twilight convenience functions. I've used them while I have been observing this week, and I repeatedly forgot if we ordered the method name as `astronomical_evening` or `evening_astronomical`. I figured that if we prefixed all method names with `twilight_*`, tab completion would make the available methods obvious (did I hear @adrn shout for joy?) and save everyone some head scratching. 
This way: 
```
% ipython
In [1]: from astroplan import Observer
In [2]: apo = Observer.at_site("APO")
In [3]: apo.twi<TAB>
apo.twilight_evening_astronomical  apo.twilight_morning_astronomical
apo.twilight_evening_civil         apo.twilight_morning_civil …
```

Renaming twilight methods to include the prefix `twilight_*`

---

astroplan/data/observatories.json
astroplan/sites.py
astroplan/tests/test_sites.py

Today @jberlanga asked me to add Subaru to the `data/observatories.json` database (just for you @ejeschke!). It made it clear to me that it would be much easier for users to create pull requests with their own observatories if they had a function that converts observatory properties to the appropriate JSON format, so I made a function that does that, and used it to create the Subaru entry. 
The new method is `new_site_info_to_json`, and can be called like this: 
```python
from astropy.coordinates import EarthLocation
from astroplan.sites import new_site_info_to_json
location = EarthLocation.from_geodetic("-155d28m34s", "+19d49m32s", 4139*u.m)
short_name = "Subaru"
aliases = ["Subaru Telescope"]
source = "Subaru Telescope website (August 2015)"
print(new_site_info_to_json(short_name, …
```

Add Subaru to observatories.json, new site-constructing method

---

astroplan/core.py
astroplan/tests/test_core.py

It's time to make some informative `__repr__` methods for `Observer` and `FixedTarget`. Here's what I've done to start the conversation: 
```python
>>> from astroplan import Observer, FixedTarget
>>> keck = Observer.at_site("Keck", timezone="US/Hawaii")
>>> print(keck)
<Observer: name=u'Keck',
location (lon, lat, el)=(-155.478333333 deg, 19.8283333333 deg, 4160.0 m),
timezone=<DstTzInfo 'US/Hawaii' LMT-1 day, 13:29:00 STD>>
>>> polaris = FixedTarget.from_name('Polaris')
>>> print(polaris)
<FixedTarget: name=u'Polaris',
coord=<SkyCoord (ICRS): (ra, dec) in deg
(37.95456067, 89.26410897)>>
```
Thoughts and feelings, @astroplanners/astroplanners-contributors?

__repr__'s for Observer, FixedTarget

---

appveyor.yml
docs/index.rst
docs/installation.rst

We should improve the Astropy continuous integration (CI) setup:
Packages that do this to look at for examples are [astropy](https://github.com/astropy/astropy) or [photutils](https://github.com/astropy/photutils)
@eteq or @adrn – Is this something you have time for? Or should we ask Brett or Jazmin if they are interested in setting this up? Alternatively I could do this next week.

Set up Windows and Mac testing

---

.continuous-integration/travis/setup_dependencies_common.sh
astroplan/conftest.py
astroplan/plots/sky.py
astroplan/plots/tests/test_sky.py
astroplan/plots/time_dependent.py
astroplan/tests/test_core.py
astroplan/tests/test_moon.py
astroplan/tests/test_sites.py
docs/installation.rst
docs/references.txt
setup.cfg

This PR makes two different changes dealing with the testing suite: First, it fixes #86 by programmatically deciding to turn pytest-mpl on or off based on whether it's installed or not. (cc @cdeil for this.)  @astrofrog my want to weigh in on whether this is a recommended way or not, too, but I think we want to merge this ASAP to allow for 0.1 to go forward, even if we go with some better way in 0.2.
Second, it changes all ``import pytest`` statements to instead be ``from astropy.tests.helper import pytest``.  The reasoning for this is that we don't want ``pytest`` to be a necessary dependency for users to run the tests.  So using the pytest packaged with astropy lets us do this without having to include pytest ourselves.  Note that this machinery still allows use of any system- installed …

Fix pytest-mpl and pytest usage

---

docs/tutorials/plots.rst
docs/tutorials/summer_triangle.rst

This comes from discussion with @eteq & @adrn about the need to be consistent with code block prompts (e.g. `>>>` at the beginning of every line) in the docs, as well as allowing doc tests to be run on those code blocks.

Simplify code block prompts & Add doc tests in some tutorials

---

astroplan/exceptions.py
astroplan/plots/sky.py
astroplan/plots/time_dependent.py

This adjusts a few areas of code so that astroplan consistently uses customized warning classes.  This is useful because it makes it easy to have fine-grained control over the warnings filter so that users can easily hide warnings that they actually expect to see.
It also adjusts the existing warnings to descend from a base `AstroplanWarning`.  Yet another layer that makes warnings control easier.

Harmonize warnings

---

.travis.yml

This adds just adds two tests to the travis test matrix that have ``--remote-data`` turned on.  This is normally pretty safe on travis because it has to be connected to the internet anyway.

Add tests with remote-data on

---

astroplan/data/observatories.json
astroplan/sites.py
astroplan/tests/test_sites.py

Ok...I'll probably get shot down on this one, but I still want to see numbers expressed as numbers! This is for 2 silly reasons: 
1. I'm making an interactive javascript visualization of the location of all observatories and I don't want to have to parse these strings to numbers, and
2. When I make a sites table in the docs (for 0.2), I want to easily generate Google earth or Google maps links from the site location for each row in the table.
I'm not concerned about precision: floating point precision correspond to ~10 nanometer differences in te site position. This also makes expression of any quantities in the JSON file consistent (e.g., before we had `elevation_meters`, now all quantities have a separate `_unit` keyword that can be passed directly into an `astropy.units.Unit()` call).

Numeric earth coords

---

.travis.yml
astroplan/conftest.py

I noticed that `test_image_example` fails when run via `astroplan.test()`:
https://gist.github.com/cdeil/f5dc761311130ff1062a#file-gistfile1-txt-L1
I'll add a travis-ci build here that tests for this case and then will try to fix it.
(My guess is that the issue is that the test image filename needs to be declared in the test decorator, so that it's installed in the tmp test folder by pytest-mpl before running the test?)

test_image_example fails when run via astroplan.test()

---

astroplan/conftest.py
astroplan/tests/test_target.py
astroplan/utils.py

This is an attempt to simplify the pytest remote data mock setup that was introduced in #98.
Please see https://github.com/astropy/astroplan/pull/98#issuecomment-137570869 and https://github.com/astropy/astroplan/pull/98#issuecomment-137680812 as well as the 
docstring of  `_mock_remote_data` in this PR where I try to explain how it works and why it's an improvement.

Simplify pytest remote data mock setup

---

docs/installation.rst

Now that `astroplan` appears in the `astropy` binstar repo via astropy/conda-builder-affiliated#54 (see [here](https://binstar.org/astropy/astroplan)), conda users can install astroplan with: 
```
conda install -c https://conda.binstar.org/astropy astroplan
```
This PR adds that line to the installation docs. cc @cdeil @eteq

Adding anaconda installation example

---

astroplan/data/observatories.json

Observatory info source: [MRO website](http://www.astro.washington.edu/users/laws/MRO/home.page/History.Basics.html).
This observatory is a fairly minor one, but one used by UW undergraduates who will be taught to use `astroplan` in their observing class.

Adding Manastash Ridge Observatory to the observatory database

---

.continuous-integration/travis/setup_dependencies_common.sh

After merging #116 the issue came up that sphinx_rtd wasn't installed, but needed for the Sphinx build (don't know why this appeared only now)?
https://travis-ci.org/astropy/astroplan/jobs/82734139#L643
So I added a `pip install sphinx_rtd` to `setup_dependencies_common.sh`, but now I'm getting this error:
https://travis-ci.org/astropy/astroplan/jobs/82742624#L613
It might be a pip or conda issue or packaging issue with one of the `sphinx_rtd` dependencies, I don't know. This seems releated: https://github.com/pypa/pip/issues/2751#issuecomment-144073543
So here I'll try installing this package differently, e.g. using pip instead of conda to install sphinx.
@astrofrog Maybe you've seen this before or have an idea what to do?

Fix sphinx_rtd install on travis-ci

---

astroplan/plots/time_dependent.py

After trying to make some demo plots using `astroplan.plots` I found some quirks to clean up. I wanted to make two subplots in one figure and noticed that the `ax.figure.autofmt_xdate()` call in `astroplan.plots.plot_airmass` is being applied to all axes within the figure, which means if you make two kinds of subplots in the same figure, you can get incorrectly rotated axis labels on other subplots like so 
Also, the time axis label in the airmass plot has a leftover hyphen in it, but doesn't show the date as I think it was supposed to. 
I've corrected these two bugs by writing a custom axis formatter and a new xlabel to go with it. The same plotting script now produces a plot like this: 
cc @jberlanga @adrn

Plot fixes

---

astroplan/moon.py
astroplan/tests/test_moon.py
astroplan/tests/test_observer.py

In #109 @cdeil found a few lines where I used a very convoluted unit conversion. I've updated the test in question to use a more straightforward unit conversion and fixed another bad test that I found for `Observer`, which wasn't doing proper unitful comparisons between expected input and output. 
@cdeil - would you mind testing this on your machine? It passes for me on Scientific Linux 6 with Python 2.7.

Potential fix for #109

---

astroplan/plots/time_dependent.py

The `astroplan.plots.plot_airmass` function calls `obs.altaz(time, target).secz`, which outputs airmass as a function of time. When the target is below the horizon, the outputs are negative (meaningless), and as a result vertical lines appear in the airmass plots at times when the target crosses the horizon. 
I've masked the airmass array to ignore negative airmasses in the plot, so that confusing vertical lines don't appear in the airmass plots, like this:
cc @jberlanga @eteq

Mask out nonsense airmasses in plot_airmass

---

astroplan/plots/sky.py

Here's a new method for `astroplan.plots` that plots a target's position as it moves through the sky over the course of 24 hours, requested in #51. Here's an example:
```python
from astroplan.plots import plot_sky_24hr
from astropy.time import Time
import astropy.units as u
from astroplan import Observer, FixedTarget
import matplotlib.pyplot as plt
vega = FixedTarget.from_name('Vega')
apo = Observer.at_site('APO')
kwargs_at_center_time = {'color': 'r', 'marker': 's', 's': 100}
plot_sky_24hr(vega, apo, Time.now(), delta=1*u.hour,
center_time_style_kwargs=kwargs_at_center_time)
plt.show()
```
I also added a new kwarg to `plot_sky` called `warn_below_horizon` which toggles the warning that comes up when a user tries to plot the position of a target that's below the horizon. This warning …

Adding requested plot_sky_24hr [#51]

---

astroplan/plots/__init__.py
astroplan/plots/mplstyles.py
astroplan/plots/sky.py
astroplan/plots/time_dependent.py
astroplan/utils.py
docs/tutorials/plots.rst

~~I've set `astroplan`'s default style sheet to be the `astropy.visualization` default style sheet~~ (update: I've undone that, see [later notes](https://github.com/astropy/astroplan/pull/127#issuecomment-149607838)), and created my own version of the astropy style sheet with a dark background for the "night mode" that we've long sought after. This should close #74. For example, here's what the airmass plot looks like now in "light" mode: 
and in "dark" mode: 
I've added a note in the plotting tutorial on how to switch between them.
cc @jberlanga @ejeschke @adrn

New style sheets for plots

---

.continuous-integration/travis/setup_dependencies_common.sh
.continuous-integration/travis/setup_environment_linux.sh
.continuous-integration/travis/setup_environment_osx.sh
ah_bootstrap.py

Miniconda's default prefix changed recently causing all travis builds failing.

Updating .travis to reflect recent miniconda changes

---

.continuous-integration/travis/setup_dependencies_common.sh
astroplan/plots/__init__.py
astroplan/plots/finder.py
docs/installation.rst
docs/references.txt
docs/rtd-pip-requirements
docs/tutorials/plots.rst

There was a mistake and an omission in PR #115 -- `plot_finder_image` was not imported into the `astroplan.plots` namespace, and no plotting tutorials were added to the docs (Issue #129). This PR seeks to fix both of those things, while cleaning up the function's docstring.
I've assigned @cdeil -- if I'm being presumptuous you don't have a few minutes to take a look in the next day or so let me know.
cc @tobyrsmith

Adding plot_finder_image docs, importing it into astroplan.plots namespace

---

astroplan/constraints.py
astroplan/tests/test_constraints.py
docs/installation.rst

This should get the tests passing again and thereby closes #138 by doing two things:
* Fixing the `SunSeparationConstraint` to properly do comparisons in the `AltAz` frame.  I'm not sure why the old version worked at all, TBH, but I think it was working only because that part of the sun transformation was buggy.  Now it transforms the sun and the targets to `AltAz` coordinates, and then does the comparison there. Note, @bmorris3, this *might* also apply to some of the other constraints - I didn't look too closely at whether or not others aren't converting to `AltAz` in places where they should be.
* It skips some doctests that are failing because there were some small changes in the rise/set results. I considered updating them, but figured it's better to skip for now, at least, because …

Fix sun constraint

---

astroplan/constraints.py
astroplan/tests/test_constraints.py

It turns out that ``AirmassConstrain(2)`` will return True for targets that are below the horizon.  While this is correct in the sense that allowing a negative airmass is meeting the requirement of "no minmum", I think it misses the point of the primary use case of wanting things to be at a higher airmass than x, while still being *up*.  So this changes the default value of  ``min`` to be 0 instead of ``None``, which strikes me as more intuitive for the typical use case.
It also adds a regression test to make sure this stays true.

Fix airmass constraint when no min is present for targets below horizon

---

astroplan/constraints.py
astroplan/tests/test_constraints.py
docs/tutorials/constraints.rst

This PR addresses a feature request in #143 from the dotastro conference for a convenience method that returns the months in which targets are observable given constraints. I've made a slow but thorough implementation of this method.  
It computes whether or not the target is observable every half hour of every day for a year, then identifies the months during times that are observable. Ideally this would be the kind of calculation that uses the trigonometric target altitude function rather than our iterative/interpolative method that propagates through `SkyCoord`->`AltAz`, adding extra computation time. But I'll leave that for a future PR.
Here's a demo script showing the functionality: 
```python
from astroplan import (FixedTarget, Observer, months_observable, 
AltitudeConstraint, …
```

Months observable [#143]

---

astroplan/constraints.py

Fixed a typo in the docs for MoonSeparationConstraint.

MoonSeparation typo

---

docs/tutorials/plots.rst

PR #162 isn't passing the CI tests. The failure seems to be stemming from the plotting tutorials, which use a time in 2015. That recent date triggers an IERS update, which raises a warning. I'm going to see if changing all 2015 dates to 2000 will fix this error.

Swapping year 2015 for 2000 in plot tutorials

---

docs/tutorials/constraints.rst

Referencing the previous section of the tutorial rather than the code block above it.

clarifying tutorial

---

docs/rtd-pip-requirements
docs/tutorials/plots.rst

Closes #163 by adding a new example plot to the narrative docs. 
I also added `wcsaxes` to the rtd requirements file, in the hopes that it will successfully plot the `plot_finder_image` [example](http://astroplan.readthedocs.io/en/latest/tutorials/plots.html#finder-chart-image), which is missing in my web browser.

plot_airmass tutorial additions

---

astroplan/constraints.py

While doing a post-hoc review of #152 (sorry about not doing that sooner, @bmorris3), I noticed that a number of the constraint docstrings were in "question-form".  That's not PEP8 compliant, but more importantly, I think it's a bit confusing, because it's not clear that the goal of the function is to *answer* that question.  So this just re-words those docstrings to be descriptive rather than "question-form".
This also removes a "to do" section that I think @bmorris3 added in #152 - my justification for that is that in my experience "todo's" can live a long time, so it's better to leave them as hints for those perusing the code rather than the documentation... But if there was a particular reason you really wanted that one in there, I can certainly remove that commit.

Constraint docstring tweaks

---

.travis.yml

~~and updates astropy-helpers to v1.1.1~~
[Edit]: updates the helpers to v1.2rc1 and closes #162

Adding build with numpy pre-release to the travis matrix

---

astroplan/plots/sky.py
astroplan/plots/time_dependent.py

This closes #102 by adding links to the RTD tutorials in the `plot_*` functions which are explained by the tutorials. This helps make the pretty narrative docs discoverable. 
Would you review, @cdeil?

Adding links to Read the Docs tutorials for plotting functions

---

.travis.yml
appveyor.yml
astroplan/conftest.py
astroplan/constraints.py
astroplan/moon.py
astroplan/observer.py
astroplan/tests/test_constraints.py
astroplan/tests/test_moon.py
astroplan/tests/test_observer.py
docs/faq/iers.rst
docs/installation.rst
docs/rtd-pip-requirements
setup.py

This is the beginning of an attempt to remove astroplan's dependence on PyEphem to calculate the moon's position (#35, #111). I say this is the "beginning" of an attempt because there is an issue with `astropy.coordinates.get_moon` which doesn't allow non-scalar time inputs (astropy/astropy#5069). I've looped over calls to `get_moon` with scalar times to produce the expected outputs until fixed. I left `TODO` notes in the functions where the workaround has been used, and if/when this PR gets merged, I'll post an issue to remind us to fix those methods once astropy/astropy#5069 is fixed.
Also note that _this PR will not pass the CI tests until astropy 1.2 is released_ (with the new solar system ephemerides features). We will need to require that astroplan uses astropy>=1.2.
On my machine, …

Swapping PyEphem moon calculations for astropy's

---

astroplan/constraints.py
astroplan/observer.py
astroplan/tests/test_constraints.py
astroplan/utils.py
docs/tutorials/constraints.rst

If I have understood the ```is_observable``` and ```is_always_observable``` routines correctly, then the ```compute_constraint``` function of a constraint should always return an array with shape ```(targets, times)```.
Presently, this is not true, with different constraints returning arrays of different shapes depending on what the shapes of the ```targets``` and ```times``` inputs. This makes the ```is_observable``` and ```is_always_observable``` routines fail when multiple ```targets``` and ```times``` are supplied and the list of constraints include constraints that return inconsistent shapes.
This PR fixes this by ensuring that all constraints return the correct shaped array. I've also added a test for this, but it is not ideal since it won't catch similar bugs in any future …

Constraint broadcasting

---

astroplan/tests/test_constraints.py

To be more consistent, and hopefully to solve @wtgee's https://github.com/astropy/astropy/issues/5202 issue.

Changing pytest import to use astropy bundled

---

astroplan/constraints.py
astroplan/tests/test_constraints.py

I made `MoonIlluminationConstraint` check whether the moon is up (`and`) when a minimum moon illumination is given, and when there is no minimum if the moon is not up (`or`). I also added a new time to the `test_moon_illumination_constraint` where the moon is below the horizon.

Require moon to be up when there is a minimum moon illumination 

---

astroplan/constraints.py
astroplan/moon.py
astroplan/observer.py

This PR removes the location keyword argument from the `moon_illumination`, `moon_phase_angle` functions in the `moon` module. 
The motivation here is that astropy's `get_moon` does not yet support computations for multiple times at a non-geocentric observer, so we were calculating each moon position with a slow `for` loop (astropy/astropy#5216). While the location of the observer on the surface of the Earth matters a lot if you want precise moon positions on the celestial sphere, it doesn't affect the result much for computing moon phase/illumination compared to a geocentric observer. So we can get vast speed-ups if we just drop the location specification here, where it doesn't matter much.
I've simply removed the `location` keyword argument, which now computes all phases/illuminations …

Removing location kwarg from moon illumination/phase computations

---

astroplan/target.py
docs/getting_started.rst
docs/tutorials/summer_triangle.rst

Here I rearrange the docs to make it easier to discover the `FixedTarget.from_name` method.
This is partially in response to a [thread on astropy-dev](https://groups.google.com/d/msg/astropy-dev/akVp7vCwebg/lK6iVFw6CAAJ) where it seems some users aren't aware of the method, probably because the docs tutorials don't use `FixedTarget.from_name` much. 
Closes #226.
cc @bsipocz @cdeil

Make the FixedTarget.from_name method easier to discover

---

astroplan/observer.py
astroplan/tests/test_observer.py

Incorrect sunset times were being reported because of lack of `horizon` check on `is_night`. This happens if you check for `tonight` after `0 deg` but before passed `horizon`.
@bmorris3 I suppose wavelength should be included too?

Fix `tonight` method to incorporate horizon at initial time check

---

.travis.yml
appveyor.yml

Conda channels now need to be explicitly listed, ci-helpers won't add astropy and astropy-ci-extras by default in the future astropy/ci-helpers#128.

Adding conda channels to CI files

---

astroplan/scheduling.py

This seems to fix the errors that are appearing with numpy1.7 in other branches (#228, #218), which I'll have to rebase or modify after this gets merged.

fix for the errors with numpy1.7

---

astroplan/scheduling.py
astroplan/tests/test_scheduling.py

I moved the `Schedule` to be something created by the user and given to the `Scheduler` as part of the call. This means that the `Scheduler` initialisation doesn't need start/end times anymore. This also means that a user doesn't need to use `schedule = scheduler(blocks)` and is reflected in the changes to the tests.

Changed how Schedulers get their Schedule.

---

astroplan/scheduling.py

Fixes #214.  PDF docs should build now.

Add one-liner docstring to Scheduler.__call__

---

astroplan/constraints.py
astroplan/tests/test_constraints.py
docs/tutorials/constraints.rst

This is an alternate form of #228, with different functions for when the score gets better or worse for larger values. Would this be better than the single function in #228?

two functions for rescaling

---

.travis.yml
appveyor.yml
astroplan/scheduling.py
astroplan/tests/test_scheduling.py
docs/tutorials/scheduling.rst

With this, both `Schedulers` can handle a previously filled schedule as their input. I will be adding another commit soon that includes this functionality in the Tutorial. This adds the desired functionality of #217 and  #209.

Using a filled schedule as input

---

.travis.yml
appveyor.yml

This should pass now and fix #248.

Removing workaround of qt version pinning

---

astroplan/tests/test_utils.py
astroplan/utils.py

This is to address the issue that came up in the astropy mailing list (time_range parameter was used rather than times, and thus silently only the first two grid elements were used only when calculating the constraint).
Probably some documentation improvement would be a better long term solution, but I'll leave that for someone else.

Input checking for ``time_range`` parameters

---

astroplan/plots/mplstyles.py

This should get rid of the ``color_cycle`` MPL warning, inspired by  astropy/astropy#5569.

Fix mpl 1.5 color_cycle deprecation warning

---

astroplan/observer.py

SkyCoords recently (new in astropy 1.3, from https://github.com/astropy/astropy/pull/5254) got an __iter__ attribute inherited from ShapedLikeNDArray, so it's not enough any more to check for the existence of that attribute to distinguish vectors from scalars.
This PR should fix the issue while also gets rid of 19 test failures against astropy dev.

Stop recognizing scalar SkyCoord objects as vectors

---

astroplan/scheduling.py

Two tests are failing because of these sphinx documentation errors. This should clean up a lot of the failures on different PRs except for the tests using numpy prerelease and astropy dev.

Small documentation fixes that should clear up some test failures

---

astroplan/conftest.py

Remote data got values in astropy 1.3, thus we need to check for that and use the mock machinery if remote-data='none'
This solves most of the issues we see with astropy stable here #278 #263 
@bmorris3 - This should also be merged asap with the other bugfixes, so only the one broadcasting issue remains.

Use mock machinery for remote-data='none'

---

astroplan/target.py

Numpy 1.12 will have a new array printing style, thus the SkyCoord changed its in astropy version 1.3 in https://github.com/astropy/astropy/pull/5423. This PR fixes the docstring examples to use the new style, and skip running doctest with older astropy versions.

Change to use new SkyCoord prints

---

.travis.yml
CHANGES.rst
appveyor.yml
astroplan/constraints.py
astroplan/observer.py
astroplan/plots/finder.py
astroplan/plots/time_dependent.py
astroplan/scheduling.py
astroplan/target.py
astroplan/tests/test_target.py
docs/installation.rst
docs/references.txt
docs/rtd-pip-requirements
docs/tutorials/plots.rst
setup.py

As described in #215, I think there's an argument for all internal calculations converting their arguments to ```Time``` and ```SkyCoord``` objects, which may be vector. This PR builds on the utility function in #215 and implements this functionality. It's a large change in the ```observer``` codebase, but outward facing functionality should be compatible with how it was before. However, there are so many unassociated test failures from other issues with astropy 1.3 it's hard to know, hence the WIP designation.
Once complete, this PR *could* fix remaining broadcasting issues with astropy 1.3 (e.g #282, #263, #272).
Some notes:
- This PR *requires* astropy 1.3 as a minimum version.
- ~~Although behaviour for scalar times and targets is unchanged, there is an improvement (IMO) in …

Fix broadcasting by using vector SkyCoords internally [WIP]

---

astroplan/scheduling.py

As outlined in the docstring for ```Transitioner```, it should return ```None``` when called with ```ObservingBlocks``` that require no transition. 
Failure to do this is causing the issues with astropy 1.3.1 mentioned in #294.
This PR makes a minor tweak to the ```Transitioner``` class so that if there is no instrument reconfiguration, and the target is identical (or the slew time is less than 1 second), the call to the ```Transition``` returns ```None```.

Transitioner should return None when no transition needed

---

astroplan/plots/time_dependent.py

This closes #259.
When `plot_airmass` is called on a target that is never above the horizon, the altitude array that gets passed to the plotting function is completely masked, and therefore a call to `ax.get_xticklabels()` throws an error. This fix checks that not all airmasses are masked before reformatting the axis.

Checking that not all points are masked before formatting time axis

---

.travis.yml
appveyor.yml
astroplan/plots/time_dependent.py

Probably we need to wait a bit more until all the dependencies become available on python 3.6, also there are quite a few failures, but nevertheless I think it's useful to have this PR opened and then later rebased once those failures are fixed.

Adding python 3.6 to CI builds

---

astroplan/scheduling.py

Hoping this is the last fix blocking the update for astropy 1.3 compatibility, which affects #296, #292, #282.

Bugfix for empty scheduling block list

---

.travis.yml
astroplan/observer.py

Support for numpy 1.7 and 1.8 as well as python 3.3 will be removed in astropy v2.0, thus it probably makes sense to remove support for them here, too.

Remove numpy 1.7 and 1.8

---

.travis.yml
appveyor.yml
astroplan/plots/tests/test_sky.py
astroplan/tests/test_constraints.py
astroplan/tests/test_observer.py
astroplan/tests/test_target.py
astroplan/tests/test_utils.py

Bundled pytest gets deprecated in astropy core in 2.0, so better to start using the system one.

Using system pytest rather than astropy bundled

---

docs/tutorials/constraints.rst

One planning visualization that I've found useful is something I call an observability grid, which shows whether or not each `Constraint` is satisfied, at several times. 
In this PR, I add a subsection to the constraints tutorial which shows you how to make it.

Updating constraints tutorial with observability grid

---

astroplan/target.py

There is an issue with astropy V2 and astroplan in that the keys of a SkyCoord's ```frame_specific_representation_info``` have changed from strings to classes.
This copes with that change. Sorry for the messy commit history. Perhaps they should all be sqaushed into one commit on merge?

Astropy V2 fix

---

.travis.yml
astroplan/constraints.py
astroplan/observer.py
docs/installation.rst
setup.py

It appears that 1.7 and 1.8 was already been dropped, but hasn't been updated in the docs or setup.py.

Dropping numpy 1.9 support

---

astroplan/scheduling.py
astroplan/tests/test_scheduling.py

This PR is inspired by difficulties I had trying to use the priority scheduler to plan an observing run. I'll describe the challenges I faced first, then my proposed fix.
I was trying to observe eclipses of short-period (<90min) binaries; and schedule many short (~20 minute) OBs to coincide with eclipses. To ensure that the scheduler does not schedule OBs too close together for a viable transition, the ```PriorityScheduler``` assumes the maximum possible transition time, and evaluates the constraints over the total time needed for the observation *plus the transition*. 
This doesn't work in my case, since my eclipse constraint is only valid for a short while, and not during the transition. As a result, none of my observations are ever scheduled.
My solution is to evaluate constraints on …

Priority scheduler logic

---

astroplan/observer.py
astroplan/target.py
astroplan/tests/test_constraints.py
astroplan/tests/test_observer.py
docs/tutorials/constraints.rst
docs/tutorials/summer_triangle.rst

This pull request implements two methods on the `Observer` object that previously raised a `NotImplementedError`. They are the `moon_rise_time` and `moon_set_time` methods, which follow the same call signature as the `sun_rise_time` and `target_rise_time` methods, just for the quickly moving moon. 
Before this PR, when calling `observer.sun_rise_time(time)`, the sun's sky coordinates were being calculated only once, at time `time`, and then the altitude of that _fixed_ coordinate was propagated forwards or backwards in time to approximate the Sun's motion throughout the day. Of course, the sun is slowly moving with respect to the celestial sphere throughout that 24 hour period, which can make a difference in rise/set times on the order of 3 minutes. 
The moon's apparent drift leads to a …

Implement moon_rise_time/moon_set_time

---

.travis.yml

hopefully this will solve the cron failure.

No need to specify pytest version any more

---

astroplan/plots/time_dependent.py

It will still set up the axes, add the brightness shading if requested, and return the axes.
This is helpful for my application because I want to start from an empty airmass chart and add my own plot elements, like this probabilistic airmass chart for a LIGO event.

Support calling plot_airmass with an empty target list

---

CHANGES.rst
astroplan/constraints.py
astroplan/tests/test_constraints.py

I've been using a pattern a lot that I think might be best implemented via a simple modification to `observability_table`.  When planning an observing run I often want to know "on a given night which objects are up for X time".  That's a bit awkward with the current observability table, because I care about actual time not just the fraction. 
The easy fix is to change it so that `time_range` can be a scalar, which means "the 24 hours surrounding this time", which then makes it easy to compute the time (it's just 24 hours * the fraction).  This then gives me a quick-and-easy way to determine "how long are my objects available given my constraints."
cc @bmorris3

Have observability_table accept scalar time

---

astroplan/constraints.py

There are two Travis tests failing that appear to be from the doctests.  The core problem appears to be that newer versions of numpy (I think 1.14 and later?) subtly changed the whitespace in how arrays get printed, which is causing doctest failures.  Adding the ``# doctest: +FLOAT_CMP`` magic here triggers a plugin that's in the helpers which changes the comparison from being a "is this string an exact match" to "are the values in this output numerically close to the expected values".  That also conveniently works around the whitespace problem.
cc @bmorris3

Fix doctest failures on new numpys

---

CHANGES.rst
astroplan/tests/test_scheduling.py

I'm not sure exactly why this worked before... my instinct would have been that directly comparing `Time` objects like this is dangerous (you don't know for sure whether they're the same format, etc).  This work-around I think fixes the failure I'm seeing on Astropy 3.0 (and I think this also then fixes #342)

Fix test failure due to time comparisons

---

astroplan/scheduling.py

When printing astropy Time objects, the scheduling code used inconsistent time formatting; some blocks would display with ISO formatting (from `start_time.iso` for example) others with JD formatting, i.e.
```
observing_blocks: [<astroplan.scheduling.ObservingBlock (NGC1807, 2018-02-25 06:00:00.267596 to 2018-02-25 06:12:40.267596) at 0x7f2b84118518>, <astroplan.scheduling.ObservingBlock (NGC1857, 2458174.845836489 to 2458174.8474568594) at 0x7f2b84118550>]
```
This PR adds `.iso` to the format strings in `scheduling.py` that did not already have ISO formatting. All Time objects in `scheduling.py` are now printed consistently. If astroplan wishes to use a different standard, that's fine and you can ignore this PR, but it should be self-consistent.

Use consistent formatting for time representation (ISO)

---

astroplan/scheduling.py

I am using astropy 3.0.1 and numpy 1.14.3. Without this patch,
`schedule.to_table()` produces this exception:
TypeError: only dimensionless scalar quantities can be converted to Python scalars

Fix error in to_table()

---

astroplan/tests/test_scheduling.py

As requested in #321 and finally delivered, a test which checks if the priority scheduler can implement short OBs which are only just shorter than the validity of their constraints

add tests for priority scheduler with short eclipses

---

astroplan/plots/sky.py

This keyword argument was deprecated in Matplotlib 2.1.0 and removed in Matplotlib 3.0.0.

Remove obsolete frac option from set_thetagrids

---

CHANGES.rst
astroplan/constraints.py
astroplan/tests/test_constraints.py

Add `GalacticPlaneSeparationConstraint` to constrain the galactic latitudes of targets. This can be useful for planning surveys for which crowding due to Galactic point sources is an issue.

Add GalacticLatitudeConstraint

---

astroplan/utils.py

[Seeking advice from: @mhvk @eteq @pllim]
Is this PR sufficient for measuring the age of an IERS table? In #436, we're getting an error when we download an old version of the IERS A table from `ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all` which appears to _not_ contain the `PolPMFlag_A` column. 
cc @tepickering and @bjweiner.
Fixes #436.

Different strategy for measuring the last date in the IERS table

---

CHANGES.rst
astroplan/observer.py
astroplan/tests/test_observer.py

Small API update, inspired by #398 and finally getting around to developing a more permanent fix for the temporary machinery implemented in https://github.com/astropy/astroplan/pull/34#issuecomment-128089175. **Note:** this PR will break backwards compatibility for an undocumented global variable of the observer module called `MAGIC_TIME`.
In #34, we designed the rise/set time functions to return a `Time` object regardless of whether or not the target actually rises or sets. In order to represent times for targets that don't rise or set, we set the rise/set time to a "magic" value, stored in `astroplan.observer.MAGIC_TIME`, which was equivalent to `Time(-999, format='jd')`. 
After discussion in astropy/astropy#4032 and others, and an update to astropy in astropy/astropy#6028, it became …

Removing MAGIC_TIME variable in favor of masked Times

---

CHANGES.rst
astroplan/observer.py
docs/tutorials/index.rst
docs/tutorials/speed.rst

**tl;dr**: you can speed up rise/set times by an order of magnitude in exchange for a few minutes of rise/set time precision, without changing anything fundamental about how astroplan/astropy compute rise/set times.
This PR implements the changes I suggested in #423, which I summarize briefly below. There are also several PEP8 compliance fixes throughout the docstrings on the Observer object. If merged, this PR supersedes #327.
The primary goal of this PR is to expose the `N` parameter, which has been lurking within the guts of the Observer object since its inception. Rise/set/transit times are computed using a grid search, which scans for horizon crossings over `N=150` times spread over 24 hours relative to the reference time supplied by the user. By throttling that parameter up or down, …

Adding `n_grid_points` parameter to rise/set/transit functions

---

astroplan/observer.py

In #424 I accidentally left the `N` in the docstrings rather than the final name of the variable `n_grid_points`. This corrects that mistake.

Fixing docstring mistakes made in #424

---

astroplan/observer.py
astroplan/tests/test_observer.py
docs/faq/iers.rst

This PR fixes an issue where using 'nearest' will result in a traceback when requesting rise/set times for an always-up source.

Avoid traceback when source is always up

---

astroplan/observer.py
astroplan/plots/time_dependent.py
astroplan/tests/test_observer.py
docs/faq/iers.rst

This PR adds support for timezone-specific airmass plots, and in the process corrects an error in which nighttime would be incorrectly unshaded if it is not centered in the plot.
Example:
Calls look like this:
```
plot_airmass(pcyg_target, CTO, now.to_datetime(timezone=CTO.timezone), use_local_tz=True, brightness_shading=True)
```
`now` is an astropy time object, `CTO` is an observatory (UF Campus Teaching Observatory).
This PR is built on https://github.com/astropy/astroplan/pull/445 but does not depend on it; it can be refactored to be separate if needed.

Timezone and shading

---

astroplan/plots/tests/test_sky.py
astroplan/plots/time_dependent.py

In Issue #452, I reported that the local timezone setting in the airmass plots wasn't working.  This PR fixes it.
I attempted to add a test, but the test doesn't really test anything at the moment, it's more of a placeholder / something you can check to make sure it looks right.  The real test is this:
```
from astropy import coordinates
from astropy import units as u
from astroplan.plots.time_dependent import plot_airmass
from astroplan import Observer
import datetime
import pytz
from astropy import log
from astropy.time import Time
log.setLevel('DEBUG')
bg = coordinates.SkyCoord.from_name('Betelgeuse')
CTO = Observer(location=coordinates.EarthLocation(lat=29.643018, lon=-82.349004*u.deg, height=31*u.m),
timezone='EST',
name='University of Florida Campus Teaching Observatory',
)
now_ET = …
```

fix timezone handling in plot_airmass

---

astroplan/__init__.py
astroplan/tests/test_constraints.py
astroplan/tests/test_observer.py
astroplan/utils.py
setup.py

Removing older code that handled the IERS downloads in favor of the new mechanism used by `astropy`.
Specifically this is relying on `astropy` to do all the heavy lifting regarding IERS. Note that I'm not doing anything clever about earlier `astropy` versions so this might not be entirely backwards compatible.  @bmorris3 we probably need to define some minimum requirement and work from there.
I've left the monkey-patching on error in here but personally I think it's a bit of an odd solution.
I've also left it so that the download happens upon initial `import astroplan`, which I also have mixed feelings about.
I'm also sneaking in one small change to a test so that things can pass (removing an extra `u.bar`). ~~My editor also reformatted some arithmetic operators so they conform to PEP so …

Astropy compatibility - download caching fixes

---

.github/workflows/ci_tests.yml

The main branch is called 'master', not 'main'.
@bmorris3 
#no-changelog-entry-needed
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

trigger tests on branch PRs

---

astroplan/scheduling.py

trying to `u.Quantity` with a string, for example, `u.Quantity([m42.ra, ''])`,
yields a `TypeError`:
```
print(u.Quantity([m42.ra, '']))
File "~/.local/lib/python3.8/site-packages/astropy/units/quantity.py", line 382, in __new__
raise TypeError("The value must be a valid Python or "
TypeError: The value must be a valid Python or Numpy numeric type.
```
this is exactly what happens in `to_table()` with transitions or unused slots
shown, because of the append `append('')` in `scheduling.py`.
so instead, do the `u.Quantity` conversion earlier where we know the type is
(should be!) a Numpy numeric (or other appropriate type).
this is, in a way, a rewrite of #370: really just moves the change there up a few lines. i tested that it works by hand on a table with `TransitionBlock`; what would …

convert quantities before they might be strings in to_table

---

astroplan/scheduling.py

Fixes #502
The priority scheduler currently requires that the inserted observing block has a duration which is an integer multiple of the time resolution, and it rounds _up_ to the nearest integer multiple observing block duration. This can lead to cases where the observing block "overflows" beyond the end of the slot by a margin similar to the time resolution. Rounding down seems to fix this.
I'd love to see if anyone can test this change on their priority schedulers before we merge this, any testers out there? Our testing of the schedulers is simple compared to some of the use cases out there, so knowing it works on someone's production code would be great!

Tweaking end of observing block in Priority Scheduler

---

astroplan/_astropy_init.py

This is probably leftover from package template. This package does not use the `astropy` configuration system at all.
Also see astropy/astropy#11497

MNT: Remove unused astropy config code

---

CHANGES.rst
astroplan/constraints.py
astroplan/tests/test_constraints.py
docs/tutorials/constraints.rst

The `time_range` appears to be fixed to 2014 in `months_observable`.
As a test I ran the code inside `months_observable`, changing the time_range to January through December 1990 and, unsurprisingly, the observable months are different. Currently, the function only applies to 2014. This optional argument is added and set with a default range of the current year, dynamically set at import. The argument is made optional for backward compatibility in function signature and the default dynamically set to a sensible intended time range.
A different output, as a Quantity array or as a Time array with the year information encoded might be more useful, but this pull request is currently a bug fix only.
Signed-off-by: Nathaniel Starkman <nstarkman@protonmail.com>

added `time_range` to `months_observable`

---

astroplan/scheduling.py

Added a "name" attribute to ObservingBlock, which can be used to assign a user-defined name or ID to a block. Should probably be used in __repr__ as well, if present.

Added a "name" attribute to ObservingBlock

---

astroplan/scheduling.py
astroplan/tests/test_scheduling.py
docs/tutorials/periodic.rst

* Replace all `np.int` instances with just `int`.
Reference: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Mentioned by @thusser in the `astroplan` slack channel. Thanks!

Update for numpy int deprecation.

---

.github/workflows/ci_tests.yml

You are using a deprecated version of `codecov-action`, see https://github.com/codecov/codecov-action for more details. xref astropy/astropy#12245
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.

MNT: Update codecov-action version to v2

---

CHANGES.rst
astroplan/observer.py
astroplan/tests/test_observer.py

Saves longitude latitude and elevation info to `Observer` class as properties to match the docs. Adds tests, docstrings, and updates changelog.
Fixes #521 (I also noticed longitude and latitude were missing).
The Linked PR addresses by adding `longitude`, `latitude`, and `elevation` methods with `@property` decorator that are re-calculated from the current `self.location` which is of type `astropy.coordinates.EarthLocation`. So that updating the location also updates the parameters. Added a meaningful test that should fail if the underlying function from `astropy` changes significantly.

Save location details to Observer instance to match the docs.

---

MANIFEST.in
astroplan/constraints.py
astroplan/exceptions.py
astroplan/observer.py
astroplan/tests/test_constraints.py
astroplan/tests/test_observer.py
setup.cfg

This PR was originally meant to address #514 from @knservis, but it widened into a few overdue improvements.
New features:
– A `MissingConstraintWarning` is raised when the user runs `months_observable(constraints, ...)` without an `AltitudeConstraint` or an `AirmassConstraint` among the constraints.
Improvements
– better handling of `nan` times within astroplan
– old manifest contents for astropy helpers are removed
– a hidden method `_process_nans_in_jds` handles the masking of "bad" times uniformly across methods within the `Observer` class
Closes #514

Adding MissingConstraintWarning warning

---

astroplan/observer.py

copied code from Observer._calc_riseset into ._calc_transit to enable calculations of lunar and solar transit.

Enabled calculation of lunar and solar transit

---

astroplan/conftest.py
astroplan/constraints.py
astroplan/moon.py
astroplan/observer.py
astroplan/tests/test_constraints.py
astroplan/tests/test_observer.py

Fixes #557
Astropy has deprecated `get_moon(time...)` in favor of `get_body('moon', time...)`. This pull request changes those calls, and catches some expected warnings in the test matrix.

Replacing deprecated astropy function: get_moon

---

astroplan/scheduling.py
astroplan/tests/test_scheduling.py

Update np.argsort() to use mergesort instead of quicksort for consistent sorting of equal values
Fixes #397

Respect the order of blocks with the same priority in PriorityScheduler

---

astroplan/observer.py
astroplan/tests/test_observer.py

Adds the ability to hash and compare Observer objects. This is helpful for adding LRU cache decorators to functions that take an Observer as a parameter.

Add __hash__, __eq__, and __ne__ support for Observer objects

---

astroplan/constraints.py
astroplan/tests/test_constraints.py

In previous versions, when setting the max parameter for altitude, max_best_rescale() would return 1.0 if the altitude exceeded the maximum limit. This behavior was unexpected.
To rectify this, the greater_than_max argument in max_best_rescale() has been set to 0. This adjustment ensures that the output aligns with expectations when the altitude surpasses the specified maximum constraint.

AltitudeConstraint: Adjust max_best_rescale() to prevent unexpected output

---

README.rst
docs/index.rst

Reintroducing RTD badge, putting `bib` reference on the main RTD page.

Further docs improvements

---

CHANGES.rst
astroplan/constraints.py

@pmaxted reported in #567 that when a (list of) `FixedTarget` is passed to methods that calculate lunar coordinates, the calls to `get_body` introduced in #558 must convert those `FixedTarget`s to `SkyCoords` before computing separations. This oversight wasn't noticed in the tests because the relevant tests rely on SkyCoords.
This PR calls `get_skycoords` before passing the `targets` to `get_body`.
Fixes #567

Convert FixedTargets passed to `get_body` into SkyCoords

---

pyproject.toml

The latest documentation from setuptools does not say that this is a recommended or required dependency.

Drop wheel from build system requirements

---

.github/workflows/ci_tests.yml

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)

MNT: Use hash for Action workflow versions and update if needed

---

astroplan/plots/finder.py

As of astropy/astroquery#2979 (May 2024), `SkyView.get_images()` no longer accepts a `grid` keyword argument. This pull request removes it from `plot_finder_image()` to prevent breakage/maintain compatibility.
Close https://github.com/astropy/astroplan/pull/591
Fixes https://github.com/astropy/astroplan/issues/588

Remove `grid` kwarg from `SkyView.get_images()` call
