.travis.yml, docs/index.rst, docs/rtd-pip-requirements, setup.py
@cdeil : Here are the requested updates assigned in Issue #6 . I think I've successfully deleted and re-made the dependencies branch on my fork of astroplan, so this PR is independent from the API discussion.
=> Documentation requested for Issue #6

astroplan/__init__.py, astroplan/core.py, docs/index.rst
Sphinx docs have not yet been generated. 
EDIT June 4: Sphinx docs generate with minor changes made to index.rst, but inheritance diagram will not show up with this commit.
=> Added skeleton source code (core.py); Modified index.rst.

astroplan/core.py, astroplan/tests/test_core.py
@astroplanners/astroplanners-contributors I've made a small, separate implementation of parallactic angle, which @eteq realized was missing from the current API.
=> Parallactic angle implementation

astroplan/core.py, astroplan/tests/test_core.py, dev/planning-example.py
Because I want to pick a fight with my past self.
=> Renaming calc_rise and calc_set to rise_time and set_time

astroplan/core.py, astroplan/tests/test_core.py
=> can_see -> target_is_up for Issue #49

astroplan/tests/test_core.py, astroplan/tests/test_sites.py
After seeing @eteq's translation of my tests for exceptions from `unitest` to `pytest` in astropy/astropy#4039, I decided to do it to. This should make @cdeil a little happy inside.
=> unittest -> pytest exceptions

astroplan/plots/__init__.py, astroplan/plots/sky.py, astroplan/plots/time_dependent.py, docs/api.rst
=> Added astroplan.plots API to docs.

.travis.yml, astroplan/plots/sky.py, astroplan/plots/time_dependent.py
- Fix some docstrings
- Change travis-ci to run on containers
=> Misc small changes

astroplan/core.py, astroplan/tests/test_core.py, astroplan/tests/test_moon.py
=> Fixing pyephem dependent tests

docs/getting_started.rst, docs/index.rst, docs/tutorials/index.rst, docs/tutorials/plots.rst, docs/tutorials/summer_triangle.rst
This was going to be a review of #42 ... but I realized it was easier to just make the changes directly.
What do you think of these, @jberlanga ?  (We can discuss it on our telecon coming up shortly if that's easier)
=> High-level docs adjustments

.continuous-integration/README.md, .continuous-integration/appveyor/install-miniconda.ps1, .continuous-integration/appveyor/windows_sdk.cmd, .continuous-integration/travis/setup_dependencies_common.sh, .continuous-integration/travis/setup_environment_linux.sh, .continuous-integration/travis/setup_environment_osx.sh, .travis.yml, appveyor.yml
This PR sets up a better test matrix for Astroplan on travis-ci.
It's a modified copy of the Astropy scripts.
Related: #38, #80
=> Set up better test matrix on travis-ci

LONG_DESCRIPTION.rst, astroplan/__init__.py, docs/index.rst
=> Improving astroplan overviews in docs

astroplan/__init__.py, astroplan/_astropy_init.py, astroplan/constraints.py, astroplan/exceptions.py, astroplan/observer.py, astroplan/plots/__init__.py, astroplan/plots/sky.py, astroplan/plots/time_dependent.py, astroplan/sites.py, astroplan/utils.py, docs/conf.py, docs/getting_started.rst, docs/tutorials/constraints.rst, docs/tutorials/plots.rst, docs/tutorials/summer_triangle.rst
I think the nitpicky option should be turned on sooner rather than later. Right now there are about ~100 broken links already in the docs. 
If you prefer I can try to fix them during the slightly toxicated sprint moments this week ;)
=> Adding nitpicky option

docs/faq/contribute.rst, docs/faq/index.rst
For #101, partly borrowed from `photutils`. cc @cdeil
=> Adding Help & Contribute page [#101]

.continuous-integration/travis/setup_dependencies_common.sh
This PR should fix the unrelated build fail in #115 by @bmorris3 :
https://travis-ci.org/astropy/astroplan/jobs/82493187#L716
This is an issue in Astropy: https://github.com/astropy/astropy/issues/4175
=> Pin coverage to version 3.7.1 on travis-ci

astroplan/plots/finder.py
This is an implementation of a simple finder chart, first implemented with examples [here](https://github.com/bmorris3/gsoc2015/blob/master/finder_chart.ipynb) (see also comments [here](https://github.com/bmorris3/gsoc2015/commit/88e06aebb7ee3cd71f4b9406302f7d62fc5266db)).
@jberlanga / @eteq / @cdeil Should we make some basic tests for this method? I wasn't following the `astroplan.plots` testing strategy very closely.
=> Simple finder chart

astroplan/plots/time_dependent.py
Adding two toggle-on features to the `plot_airmass` method: 
1. `brightness_shading` shades the background according to the darkness of the sky (light shading for 0 deg twilight, darker for -18 deg twilight)
2. `altitude_yaxis` adds a new y-axis on the right side of the figure with the equivalent altitudes in degrees. See below for an example plot with both options on:
```python
from astroplan.plots import plot_airmass
import matplotlib.pyplot as plt
from astropy.time import Time
from astroplan import FixedTarget, Observer
time = Time.now()
target = FixedTarget.from_name('HD 189733')
apo = Observer.at_site('APO')
plot_airmass(target, apo, time, brightness_shading=True, altitude_yaxis=True)
plt.show()
```
cc @eteq @ejeschke @Barentsen
=> Adding airmass plot options

astroplan/plots/time_dependent.py
=> Removing print statements for debugging

astroplan/plots/time_dependent.py
Using @jakevdp's hack for detecting twin axes, and preventing multiple twin axes from being drawn in the airmass plot.
=> Plot airmass

README.rst
RTD, appveyor and pypi. 
The RTD is especially useful I think as there is not much feedback if the builds got stuck.
=> Adding more badges to the Readme page

astroplan/constraints.py, astroplan/tests/test_constraints.py
I added classmethods for default values for dark, grey, and bright time into `MoonIlluminationConstraint`
=> added dark, grey, and bright classmethods

astroplan/observer.py, astroplan/tests/test_observer.py
Cleaner implementation of #196 along with tests. Closes #196 
(small pep8 cleanup included in `observer.py`)
=> Tonight convenience method

astroplan/scheduling.py
Mostly just cleanup code as per #206
=> Moving methods to the base `Scheduler` class

astroplan/scheduling.py
I wrote up a scorer. It isn't currently being used, but once I take the time to move the `PriorityScheduler` over to it, it should make it easier to modify, optimize, and show how scoring is being done.
=> Creating a Scorer

astroplan/constraints.py
No change to functionality. (Fixed the branch it was coming from)
=> Small spelling and name fixes

astroplan/plots/time_dependent.py
* Accept either a single target or a list of targets
* Brightness shading that actually works (from @joshwalawender in panoptes/PEAS)
**Note: Really this should all be redone to use a real plt.figure and axes**
=> Plot Airmass Improvments

astroplan/scheduling.py, astroplan/tests/test_scheduling.py
Added some tests for the scorer (#210).
=> Scorer testing

astroplan/constraints.py, astroplan/observer.py, astroplan/scheduling.py, astroplan/target.py, astroplan/tests/test_constraints.py, astroplan/utils.py
I went through most of the files and fixed typos and PEP 8 issues that I found. This can be merged if it doesn't interfere with anybody's changes.
=> PEP 8 issues and typos

astroplan/scheduling.py
With this, the priority scheduler makes use of the scorer. The main benefit is that it vectorizes global constraints.
=> using scorer in priority scheduler

astroplan/scheduling.py, docs/tutorials/plots.rst, docs/tutorials/scheduling.rst, docs/tutorials/summer_triangle.rst
This adds a tutorial for making a user-defined `Scheduler`.
=> added a user-defined scheduler tutorial and fixed x-axis label cut-offs

docs/installation.rst
In accordance with @mwcraig's suggestion in #249.
=> Abbreviating conda install command

astroplan/plots/time_dependent.py
=> Fixes the incorrect shading on certain dates by sorting the datetimes

astroplan/observer.py, astroplan/scheduling.py
=> Fixing parameter lists

astroplan/constraints.py, astroplan/moon.py, astroplan/observer.py, astroplan/plots/sky.py, astroplan/scheduling.py
This PR addresses the comment https://github.com/astropy/astroplan/pull/213#issuecomment-273977071 and checks the consistency of other parameter list and removes/adds parameters as required.
=> Cleaning up parameters

astroplan/observer.py
Small fixes for some tests as discussed in #282
=> Small fixes for astropy 1.3 as discussed in #282

.travis.yml
Apparently we were comparing apples to pears...
Fix #287 for more info see astropy/astropy#5810
=> Fixing coverage reporting

LICENSE.rst, licenses/LICENSE.rst, licenses/README.rst
Somehow this directory was missing here, so I've copied it over from the template.
=> Add license

ah_bootstrap.py
This is an automated update of the astropy-helpers submodule to v2.0.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.
*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*
=> Update astropy-helpers to v2.0.1

astroplan/constraints.py, astroplan/observer.py, astroplan/target.py, astroplan/tests/test_constraints.py, astroplan/tests/test_moon.py, astroplan/tests/test_observer.py
Building on @adrn's earlier PR.
=> Compatibility with coordinates v2.0

astroplan/constraints.py, astroplan/observer.py, astroplan/target.py, astroplan/tests/test_constraints.py, astroplan/tests/test_moon.py, astroplan/tests/test_observer.py
=> Updates to be compatible with astropy.coordinates in v2.0

.travis.yml
also updating the python version astropy dev tested with as we're about to remove py2.7 support in dev
=> Test for the recent pytest version

MANIFEST.in, docs/paper/paper.bib, docs/paper/paper.md
More notes on this PR after the tests finish running...
=> Prepping JOSS submission

ez_setup.py
This is an automated update of the astropy-helpers submodule to v2.0.2. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.
*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*
=> Update astropy-helpers to v2.0.2

docs/index.rst
...from the docs front-page, which used to say that the API was unstable. @eteq – if you're comfortable with this decision, feel free to merge!
=> Removing big warning

astroplan/plots/time_dependent.py
Reworking airmass plot enhancements from @ejeschke. This PR supersedes and closes #158.
=> Added kwarg parameters for limits and regions to plot_airmass

astroplan/scheduling.py, astroplan/tests/test_constraints.py
For compatibility post astropy/astropy#6590
=> Fixing boolean quantity evaluations

astroplan/conftest.py
=> update pyephem import

docs/getting_started.rst, docs/tutorials/plots.rst, docs/tutorials/summer_triangle.rst
Today I learned that the appropriate spelling of Maunakea should be as one word [[source](http://www.malamamaunakea.org/articles/9/Maunakea)]. I've corrected the spelling throughout the package.
=> Correcting spelling of Maunakea

README.rst
At the suggestion of @arfon at #pyastro18.
=> Adding citation bibtex entry

astroplan/plots/time_dependent.py, docs/tutorials/plots.rst
Fix for issues #362, #363 and #364! cc @abostroem
=> Adding docs and plot_altitude function

astroplan/scheduling.py
=> Duck typing for @ehneilsen

astroplan/observer.py
=> Fix docstring for `observer.sun_altaz`

.travis.yml, appveyor.yml, astroplan/conftest.py, docs/installation.rst, docs/references.txt, setup.py
@bmorris3 - This should fix the issues you see in #386. 
(except of course #382 that is still an issue)
=> Using explicit imports to fix pytest 3.7+ issue

astroplan/observer.py
Use the arctan2 function for parallactic angle to return the proper range of parallactic angles, fixing issue #385.
=> Fix issue #385

astroplan/observer.py
=> Fixing docs on moon_phase

astroplan/plots/time_dependent.py
when airmass_yaxis=True is used
=> plot_altitude(): set correct ylabel

docs/tutorials/periodic.rst
Swapping the Exoplanet Orbit Database for the NASA Exoplanet Archive in the documentation. 
Fixes #430.
=> Update docs with NASA Exoplanet Archive

astroplan/tests/test_observer.py, docs/faq/precision.rst
Fixes #409, with some great help from @tepickering.
=> Adding sunrise/set precision discussion in FAQ, tests against MMTO

docs/faq/iers.rst
Fixes a minor issue causing travis failures
=> remove astropy.extern.six usage in docs

astroplan/plots/sky.py
The number of theta_labels (7) didn't match
the number of ticks.
=> Fix to issue #468

.readthedocs.yml, README.rst
May contribute to fixing #495.
=> Adding readthedocs config file v2

docs/installation.rst
Similar to astropy/astropy#11111
cc @mwcraig
=> DOC: Replace astropy channel with conda-forge

docs/tutorials/periodic.rst
pl_trandur already has the unit of days. I assume that this is from an upstream change in astroquery
=> Unit error in periodic tutorial

.github/workflows/ci_tests.yml, astroplan/scheduling.py, docs/faq/iers.rst
This PR attempts to replace all mention of `master` to `main` in this repository. This should be reviewed and merged right after the maintainer has renamed the default branch.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
This is part of #504
=> MNT: Replace master with main

.readthedocs.yml, astroplan/plots/finder.py, astroplan/plots/sky.py, astroplan/scheduling.py, docs/conf.py, docs/tutorials/plots.rst, setup.cfg
Some fixes that I came across while working on #522.
=> Fixes to build_docs

CITATION.bib
Now supported by GitHub for easy-to-export citations from the webpage: 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#other-citation-files
=> Update and rename CITATION to CITATION.bib

.github/workflows/ci_tests.yml
I got pinged about #512 so might as well. 😸
=> TST: Update Action versions

.github/workflows/ci_tests.yml
Updating Python versions all around, adding tests for 3.11.
=> Modernizing CI workflow

astroplan/plots/time_dependent.py
=> Improve plot_schedule_airmass() performance by drawing night bands only once

astroplan/plots/time_dependent.py
Reverts astropy/astroplan#540. It seems there's a bug still to sort out in astropy/astroplan#540.
=> Revert "Improve plot_schedule_airmass() performance by drawing night bands only once"

CHANGES.rst, astroplan/plots/sky.py, astroplan/plots/time_dependent.py, docs/conf.py, docs/getting_started.rst, docs/index.rst, docs/installation.rst, docs/tutorials/plots.rst, setup.cfg
Moving to a more modern template, and fixing up some plots.
=> Docs improvements, new theme

docs/_templates/layout.html, docs/conf.py, docs/index.rst, docs/robots.txt
Some updates to documentation to improve the version slug on RTD.
=> Docs revisions

tox.ini
I updated python, numpy, astropy versions in tox.ini. LMK if it looks ok. Thanks.
=> Fix to issue #555 - Updating test matrix

setup.cfg
This reverts commit df7f1d39679581fe58c8eaf9201adc0df2bade57.
=> Support Numpy 1.x and 2.x
